
CREATE TABLE test.MESSAGE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    version BIGINT,
    ID_EVENT VARCHAR(255),
    topic VARCHAR(255),
    payload LONGTEXT,
    status VARCHAR(50),
    SEND_TIMESTAMP TIMESTAMP NULL,
    CREATE_TIMESTAMP TIMESTAMP NULL,
    attempts INT NOT NULL
);


CREATE TABLE test.ORDER_AVAILABLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    cost DECIMAL(19,2),
    STATUS_STOCK VARCHAR(50),
    INSERT_ORDER TIMESTAMP NULL,
    ID_EVENT VARCHAR(255)
);


CREATE TABLE test.ORDER_DLQ (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    cost DECIMAL(19,2),
    notification BOOLEAN NOT NULL,
    ID_EVENT VARCHAR(255)
);


CREATE TABLE test.ORDER_STOCK_DLQ (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    cost DECIMAL(19,2),
    available VARCHAR(50),
    notification BOOLEAN NOT NULL,
    ID_EVENT VARCHAR(255)
);
