replicaCount: 1

image:
  repository: mysql
  tag: "8.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

mysql:
  rootPassword: rootpwd
  database: appdb
  user: appuser
  password: apppwd

persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce